<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="35" total="36" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-10-03T22:31:49 PDT" name="Suite1" finished-at="2022-10-03T22:32:20 PDT" duration-ms="31172">
    <groups>
    </groups>
    <test started-at="2022-10-03T22:31:49 PDT" name="Firefox Tests" finished-at="2022-10-03T22:32:20 PDT" duration-ms="31172">
      <class name="com.firebase.test.tests.AutomationTest">
        <test-method is-config="true" signature="setupBeforeTest()[pri:0, instance:com.firebase.test.tests.AutomationTest@61fe30]" started-at="2022-10-03T22:31:49 PDT" name="setupBeforeTest" finished-at="2022-10-03T22:31:49 PDT" duration-ms="124" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupBeforeTest -->
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.reflect.Method)[pri:0, instance:com.firebase.test.tests.AutomationTest@61fe30]" started-at="2022-10-03T22:31:49 PDT" name="setUp" finished-at="2022-10-03T22:31:53 PDT" duration-ms="3186" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public static void com.firebase.test.tests.AutomationTest.salesforceTC33() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="salesforceTC33()[pri:0, instance:com.firebase.test.tests.AutomationTest@61fe30]" started-at="2022-10-03T22:31:53 PDT" name="salesforceTC33" finished-at="2022-10-03T22:32:14 PDT" duration-ms="21686" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://cricketinusa-dev-ed.develop.my.salesforce.com/_ui/core/userprofile/UserProfilePage?tab=sfdc.ProfilePlatformFeed] but found [https://cricketinusa-dev-ed.develop.my.salesforce.com/_ui/core/userprofile/UserProfilePage?u=0054x000005QGjo&tab=sfdc.ProfilePlatformFeed]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://cricketinusa-dev-ed.develop.my.salesforce.com/_ui/core/userprofile/UserProfilePage?tab=sfdc.ProfilePlatformFeed] but found [https://cricketinusa-dev-ed.develop.my.salesforce.com/_ui/core/userprofile/UserProfilePage?u=0054x000005QGjo&tab=sfdc.ProfilePlatformFeed]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.firebase.test.tests.AutomationTest.salesforceTC33(AutomationTest.java:891)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- salesforceTC33 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.firebase.test.tests.AutomationTest@61fe30]" started-at="2022-10-03T22:32:14 PDT" name="tearDown" finished-at="2022-10-03T22:32:20 PDT" duration-ms="5592" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="tearDownAfterTest()[pri:0, instance:com.firebase.test.tests.AutomationTest@61fe30]" started-at="2022-10-03T22:32:20 PDT" name="tearDownAfterTest" finished-at="2022-10-03T22:32:20 PDT" duration-ms="549" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterTest -->
      </class> <!-- com.firebase.test.tests.AutomationTest -->
    </test> <!-- Firefox Tests -->
  </suite> <!-- Suite1 -->
</testng-results>
